### ISSUE TITLE
Error: cannot create note because it is empty

### ISSUE THREAD

**Issue by Pierre33400** [OoDeLally/anki-add-hooks-userscripts#32] opened 2019-09-13 07:05 UTC
I get this error message when I click on the Add button: "cannot create note because it is empty". What could be the problem?

**Comment by OoDeLally** [comment] 2019-09-18 10:28
I recently fixed a bug for Lingea.cz. If your issue happens in Lingea.cz, please try with the last version first.

If it still fails, it probably means that it failed to get the content from the page. It may be caused by bad selectors, or the website updated its html formatting.
Could you give me the page where this appeared?

**Comment by Pierre33400** [comment] 2019-09-21 07:28
I have the last version. The problem is with wordreference, for example on this page:
https://www.wordreference.com/enfr/doodle

**Comment by OoDeLally** [comment] 2019-09-21 13:46
This page seems to work fine for me.
Which entry do you try to add on this page?
Can you tell me what browser you use, what version?
Thank you

**Comment by Pierre33400** [comment] 2019-09-22 14:15
Any entry, and on any page of WR.
My user agent is Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0

**Comment by OoDeLally** [comment] 2019-09-23 18:45
Tampermonkey or Greasemonkey? What version?
I tried with Firefox 69 and the latest version of both Tampermonkey and Greasemonkey, without finding any issue.
Thank you

**Comment by Pierre33400** [comment] 2019-09-25 11:20
Tampermonkey, 4.9.5941 (2019-05-04)

**Comment by OoDeLally** [comment] 2019-09-25 15:08
I am still unable to reproduce the issue although I use the same version as you for everything. 
Could you post a screenshot? Thank you

**Comment by Pierre33400** [comment] 2019-09-26 00:04
![image](https://user-images.githubusercontent.com/2399161/65648305-04682000-e002-11e9-8ece-ad3d92756c1c.png)

**Comment by OoDeLally** [comment] 2019-09-27 22:32
Thank you. I updated the WordReference script. There was a bug that prevented to display the error correctly. Could you update your script and try again?
I don't think it will solve your bug, but at least the displayed error will be more explicit.
Thank you

**Comment by Pierre33400** [comment] 2019-09-29 19:36
It works now! Apparently the problem was with field names of my Basic notes, they were not named Front and Back.

**Comment by OoDeLally** [comment] 2019-09-29 21:44
How were they called? Did you customize the name yourself, or are there programs using different default names?

**Comment by Pierre33400** [comment] 2019-10-01 17:55
I think I customized them long ago.
(But in my Anki install there is also a note type called "Basique" (it means Basic in French), with fields "Recto" and "Verso", and I think this is one of the default note types I have)

**Comment by OoDeLally** [comment] 2019-10-01 22:07
Ok I understand. 
I tried adding a note after changing `Front` to `Front1`, and I got the same `cannot create note because it is empty` that you had. 
This is likely the error message from AnkiConnect when one of the expected field is not filled, and it isn't indeed very clear.

There seems to be a way to fetch in advance the available card model and field names (https://github.com/FooSoft/anki-connect). So I'll try to use that, so no one has this problem again.

**Comment by OoDeLally** [comment] 2019-10-02 10:54
246e6b8c41febc669cda751428c8bdd5afbc543f
6c3cc3dd6d97a28d23490b3665b43fe84f1295c8

I made the change. Could you try with your "Recto/Version" fields? Thank you.

**Comment by OoDeLally** [comment] 2019-10-06 11:55
Closing this. Please reopen in case the problem is not solved.

**Closed by OoDeLally** 2019-10-06 11:55 UTC
Labels: bug

**Comment by Pierre33400** [comment] 2019-10-07 13:52
"Could you try with your "Recto/Version" fields?"
Yes, that works.
